// lib/pdfGenerator.ts
// Generates a properly formatted A4 PDF using jsPDF.
// Always outputs in English regardless of app language.
// Run: npm install jspdf

import type { PlanResult } from '@/types'
import type { Lang } from '@/types'

export async function generateItineraryPDF(result: PlanResult, _lang?: Lang): Promise<void> {
  const { jsPDF } = await import('jspdf')

  // Always English
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  // ─── Palette ─────────────────────────────────────────────────
  type RGB = [number, number, number]
  const RED         = [185, 28,  28]  as RGB
  const RED_PALE    = [254, 226, 226] as RGB
  const RED_DARK    = [127, 29,  29]  as RGB
  const RED_LIGHT   = [252, 165, 165] as RGB
  const INK         = [28,  28,  28]  as RGB
  const INK2        = [92,  85,  85]  as RGB
  const INK3        = [154, 144, 144] as RGB
  const WHITE       = [255, 255, 255] as RGB
  const BORDER      = [232, 222, 222] as RGB
  const SURFACE2    = [245, 237, 237] as RGB
  const AMBER_PALE  = [254, 243, 199] as RGB
  const AMBER_TXT   = [146, 64,  14]  as RGB
  const NAVY        = [30,  58,  95]  as RGB

  const PAGE_W  = 210
  const MARGIN  = 16
  const CONTENT = PAGE_W - MARGIN * 2
  let y = 0

  // ─── Helpers ─────────────────────────────────────────────────
  const fmt = (n: number) => n.toLocaleString('en-US')

  function newPage() { doc.addPage(); y = MARGIN }
  function checkBreak(needed: number) { if (y + needed > 280) newPage() }

  function fc(rgb: RGB) { doc.setFillColor(rgb[0], rgb[1], rgb[2]) }
  function tc(rgb: RGB) { doc.setTextColor(rgb[0], rgb[1], rgb[2]) }
  function dc(rgb: RGB) { doc.setDrawColor(rgb[0], rgb[1], rgb[2]) }

  function filledRect(x: number, yp: number, w: number, h: number, fill: RGB, r = 0) {
    fc(fill); dc(fill); doc.setLineWidth(0)
    r > 0 ? doc.roundedRect(x, yp, w, h, r, r, 'F') : doc.rect(x, yp, w, h, 'F')
  }
  function strokeRect(x: number, yp: number, w: number, h: number, stroke: RGB, r = 0, lw = 0.3) {
    dc(stroke); doc.setLineWidth(lw)
    r > 0 ? doc.roundedRect(x, yp, w, h, r, r, 'S') : doc.rect(x, yp, w, h, 'S')
  }
  function hLine(yp: number, col: RGB = BORDER) {
    dc(col); doc.setLineWidth(0.25); doc.line(MARGIN, yp, PAGE_W - MARGIN, yp)
  }
  function txt(
    s: string,
    x: number,
    yp: number,
    opts?: { align?: 'left' | 'center' | 'right'; maxWidth?: number }
  ) {
    // Sanitize: strip non-latin characters to avoid glyph issues
    const safe = s.replace(/[^\x00-\x7F]/g, '')
    doc.text(safe || s, x, yp, opts)
  }
  function badge(label: string, x: number, yp: number, bg: RGB, fg: RGB) {
    doc.setFontSize(6.5); tc(fg)
    const w = doc.getTextWidth(label) + 5
    filledRect(x, yp - 3, w, 4.5, bg, 1.2)
    txt(label, x + 2.5, yp)
    return w
  }
  function sectionTitle(label: string, yp: number) {
    doc.setFontSize(7.5); doc.setFont('helvetica', 'bold'); tc(RED)
    txt(label, MARGIN, yp)
  }

  // ─── HEADER ──────────────────────────────────────────────────
  filledRect(0, 0, PAGE_W, 28, RED_DARK)
  // Subtle gradient overlay
  filledRect(0, 0, PAGE_W, 28, [127, 29, 29])

  doc.setFontSize(15); doc.setFont('helvetica', 'bold'); tc(WHITE)
  txt('RAIZEN', MARGIN + 2, 13)
  doc.setFontSize(7); doc.setFont('helvetica', 'normal'); tc(RED_LIGHT)
  txt('Myanmar Travel Planner', MARGIN + 2, 19)

  doc.setFontSize(7); tc(RED_LIGHT)
  txt(
    new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
    PAGE_W - MARGIN, 11, { align: 'right' }
  )
  txt('raizentravel.com', PAGE_W - MARGIN, 17, { align: 'right' })

  // Decorative right bar
  filledRect(PAGE_W - 8, 0, 8, 28, RED)

  y = 36

  // ─── TRIP TITLE ──────────────────────────────────────────────
  doc.setFontSize(20); doc.setFont('helvetica', 'bold'); tc(INK)
  txt(`${result.days}-Day ${result.destinationName} Trip`, MARGIN, y)
  y += 7

  doc.setFontSize(9); doc.setFont('helvetica', 'normal'); tc(INK2)
  txt(
    `${result.travelerLabel.en}  ·  ${result.departureLabel.en}  ·  Generated by Raizen`,
    MARGIN, y
  )
  y += 5

  hLine(y); y += 8

  // ─── TRIP CHIPS ──────────────────────────────────────────────
  const chips = ['Beach Trip', 'Bus Included', 'Hotel Matched', 'PDF Itinerary']
  let chipX = MARGIN
  chips.forEach((chip) => {
    doc.setFontSize(7); doc.setFont('helvetica', 'bold'); tc(RED)
    const w = doc.getTextWidth(chip) + 8
    filledRect(chipX, y - 3.5, w, 5.5, RED_PALE, 2)
    txt(chip, chipX + 4, y)
    chipX += w + 4
  })
  y += 8

  // ─── SEASON BOX ──────────────────────────────────────────────
  checkBreak(18)
  filledRect(MARGIN, y, CONTENT, 14, NAVY, 3)
  doc.setFontSize(7); doc.setFont('helvetica', 'bold'); tc([255, 255, 255])
  tc([180, 200, 230] as RGB)
  txt('BEST TRAVEL SEASON', MARGIN + 5, y + 5.5)
  doc.setFontSize(9); doc.setFont('helvetica', 'bold'); tc(WHITE)
  txt('Nov - Apr  |  Dry Season  |  Clear skies, calm sea, perfect for beach', MARGIN + 5, y + 11)
  doc.setFontSize(9); doc.setFont('helvetica', 'bold'); tc(WHITE)
  txt('32 C', PAGE_W - MARGIN - 4, y + 9, { align: 'right' })
  y += 20

  // ─── BUS TICKET ──────────────────────────────────────────────
  checkBreak(32)
  sectionTitle('BUS TICKET', y); y += 5

  filledRect(MARGIN, y, CONTENT, 22, RED, 3)

  doc.setFontSize(9); doc.setFont('helvetica', 'bold'); tc(WHITE)
  txt('BUS', MARGIN + 5, y + 10)

  doc.setFontSize(11); doc.setFont('helvetica', 'bold'); tc(WHITE)
  txt(result.busTicket.route, MARGIN + 20, y + 8)

  doc.setFontSize(7.5); doc.setFont('helvetica', 'normal'); tc(RED_LIGHT)
  const paxCount = result.busTicket.pricePerPax > 0
    ? result.busTicket.totalPrice / result.busTicket.pricePerPax : 0
  txt(`Round Trip  |  ${paxCount} pax`, MARGIN + 20, y + 14)
  if (result.busTicket.note) {
    doc.setFontSize(6.5); tc([255, 200, 200] as RGB)
    txt(result.busTicket.note, MARGIN + 20, y + 19)
  }

  doc.setFontSize(13); doc.setFont('helvetica', 'bold'); tc(WHITE)
  txt(`${fmt(result.busTicket.totalPrice)} MMK`, PAGE_W - MARGIN - 2, y + 9, { align: 'right' })
  doc.setFontSize(7); doc.setFont('helvetica', 'normal'); tc(RED_LIGHT)
  txt(`${fmt(result.busTicket.pricePerPax)} x ${paxCount} pax`, PAGE_W - MARGIN - 2, y + 15, { align: 'right' })

  y += 28

  // ─── COST SUMMARY ────────────────────────────────────────────
  checkBreak(40)
  sectionTitle('COST SUMMARY', y); y += 5

  strokeRect(MARGIN, y, CONTENT, 32, BORDER, 3)

  const costRows = [
    { label: 'Bus Tickets (round trip)', value: `${fmt(result.busTicket.totalPrice)} MMK` },
    {
      label: `Hotel (${result.days} nights, cheapest match)`,
      value: result.cheapestHotelTotal > 0 ? `${fmt(result.cheapestHotelTotal)} MMK` : 'No match',
    },
  ]
  costRows.forEach((row, i) => {
    const ry = y + 8 + i * 10
    doc.setFontSize(8.5); doc.setFont('helvetica', 'normal'); tc(INK2)
    txt(row.label, MARGIN + 4, ry)
    doc.setFont('helvetica', 'bold'); tc(INK)
    txt(row.value, PAGE_W - MARGIN - 4, ry, { align: 'right' })
    if (i < costRows.length - 1) hLine(ry + 4.5, BORDER)
  })

  const totalY = y + 24
  filledRect(MARGIN, totalY, CONTENT, 9, RED_PALE, 2)
  doc.setFontSize(8.5); doc.setFont('helvetica', 'bold'); tc(RED)
  txt('Estimated Minimum Total', MARGIN + 4, totalY + 6)
  doc.setFontSize(11); tc(RED)
  txt(`${fmt(result.totalCost)} MMK`, PAGE_W - MARGIN - 4, totalY + 6, { align: 'right' })

  y += 40

  // ─── MATCHED HOTELS ──────────────────────────────────────────
  checkBreak(18)
  sectionTitle('MATCHED HOTELS FOR YOUR BUDGET', y); y += 5

  if (result.matchedHotels.length === 0) {
    doc.setFontSize(8.5); doc.setFont('helvetica', 'normal'); tc(INK3)
    txt('No hotels found within this budget.', MARGIN, y); y += 8
  } else {
    for (const hotel of result.matchedHotels) {
      const hh = 13 + hotel.matchedRooms.length * 9 + 4
      checkBreak(hh)
      strokeRect(MARGIN, y, CONTENT, hh, BORDER, 3)
      filledRect(MARGIN, y, CONTENT, 13, SURFACE2, 3)
      hLine(y + 13, BORDER)

      doc.setFontSize(10); doc.setFont('helvetica', 'bold'); tc(INK)
      txt(hotel.name, MARGIN + 4, y + 9)
      const badgeX = MARGIN + 4 + doc.getTextWidth(hotel.name) + 4
      badge(hotel.tier, badgeX, y + 9, AMBER_PALE, AMBER_TXT)

      doc.setFontSize(7); doc.setFont('helvetica', 'normal'); tc(INK3)
      txt('From', PAGE_W - MARGIN - 4, y + 6, { align: 'right' })
      doc.setFontSize(9); doc.setFont('helvetica', 'bold'); tc(RED)
      txt(`${fmt(hotel.minPrice)} MMK`, PAGE_W - MARGIN - 4, y + 11, { align: 'right' })

      let ry = y + 17
      hotel.matchedRooms.forEach((room, ri) => {
        doc.setFontSize(8); doc.setFont('helvetica', 'normal'); tc(INK2)
        txt(room.roomType, MARGIN + 4, ry)
        doc.setFont('helvetica', 'bold'); tc(INK)
        txt(`${fmt(room.pricePerNight)}/night`, PAGE_W - MARGIN - 4, ry, { align: 'right' })
        doc.setFontSize(6.5); doc.setFont('helvetica', 'normal'); tc(RED)
        txt(
          `${fmt(room.pricePerNight)} x ${result.days} nights = ${fmt(room.totalForStay)} MMK`,
          PAGE_W - MARGIN - 4, ry + 4.5, { align: 'right' }
        )
        if (ri < hotel.matchedRooms.length - 1) hLine(ry + 6, BORDER)
        ry += 9
      })
      y += hh + 4
    }
  }

  y += 2

  // ─── DAY PLANS ───────────────────────────────────────────────
  checkBreak(18)
  sectionTitle('DAY-BY-DAY PLAN', y); y += 5

  for (const day of result.dayPlans) {
    const actCount = day.activities.length
    const dh = 12 + actCount * 14 + 4
    checkBreak(dh)

    strokeRect(MARGIN, y, CONTENT, dh, BORDER, 3)
    filledRect(MARGIN, y, CONTENT, 10, RED_PALE, 3)
    hLine(y + 10, [240, 200, 200] as RGB)

    doc.setFontSize(7.5); doc.setFont('helvetica', 'bold'); tc(RED)
    txt(`Day ${day.dayNumber}`, MARGIN + 4, y + 7)
    doc.setFontSize(8.5); doc.setFont('helvetica', 'bold'); tc(INK)
    txt(day.titleEn, MARGIN + 22, y + 7)

    let ay = y + 15
    day.activities.forEach((act) => {
      doc.setFontSize(7.5); doc.setFont('helvetica', 'bold'); tc(INK3)
      txt(act.time_en, MARGIN + 4, ay)
      doc.setFont('helvetica', 'bold'); tc(INK)
      txt(act.name_en, MARGIN + 22, ay)
      doc.setFontSize(7); doc.setFont('helvetica', 'normal'); tc(INK3)
      const lines = doc.splitTextToSize(act.detail_en, CONTENT - 26)
      txt(lines[0] ?? '', MARGIN + 22, ay + 5)
      ay += 14
    })
    y += dh + 4
  }

  // ─── TIPS ─────────────────────────────────────────────────────
  const tips = [
    'During peak travel seasons, bus tickets and hotel bookings often become fully booked. Therefore, it is best to make your reservations at least 3 weeks in advance.',
  ]

  checkBreak(34)
  y += 4
  sectionTitle('TIPS', y); y += 5

   const tipLines = tips.flatMap((tip) => doc.splitTextToSize(tip, CONTENT - 16))
  const tipsH = tipLines.length * 5 + 8
  strokeRect(MARGIN, y, CONTENT, tipsH, BORDER, 3)
  tipLines.forEach((line, i) => {
    const ty = y + 7 + i * 5
    if (i === 0) {
      fc(RED); doc.setLineWidth(0)
      doc.circle(MARGIN + 5.5, ty - 1, 1, 'F')
    }
    doc.setFontSize(8); doc.setFont('helvetica', 'normal'); tc(INK2)
    txt(line, MARGIN + 10, ty)
  })
  y += tipsH + 6
  
  // ─── VIBER CONTACT ────────────────────────────────────────────
  checkBreak(28)
  filledRect(MARGIN, y, CONTENT, 24, [243, 240, 255] as RGB, 3)
  strokeRect(MARGIN, y, CONTENT, 24, [115, 96, 242] as RGB, 3, 0.3)

  doc.setFontSize(9); doc.setFont('helvetica', 'bold'); tc([61, 45, 142] as RGB)
  txt('Need help booking this trip?', MARGIN + 5, y + 7)
  doc.setFontSize(7.5); doc.setFont('helvetica', 'normal'); tc([92, 75, 190] as RGB)
  txt('Call: 09682880475  |  Viber: 09751067759  |  Response within 1 hour', MARGIN + 5, y + 13)
  doc.setFontSize(7); tc([115, 96, 242] as RGB)
  txt('raizentravel.com', MARGIN + 5, y + 19)

  y += 30

  // ─── FOOTER ──────────────────────────────────────────────────
  checkBreak(16)
  hLine(y, BORDER); y += 5
  doc.setFontSize(7.5); doc.setFont('helvetica', 'normal'); tc(INK3)
  txt('Raizen Myanmar  |  raizentravel.com  |  vibeauto3@gmail.com', PAGE_W / 2, y, { align: 'center' })
  y += 4
  doc.setFontSize(7); tc(RED)
  txt('Generated with Raizen - Real MMK Prices, Real Hotels.', PAGE_W / 2, y, { align: 'center' })

  // ─── PAGE NUMBERS ─────────────────────────────────────────────
  const totalPages = (doc as any).internal.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFontSize(7); doc.setFont('helvetica', 'normal'); tc(INK3)
    txt(`${i} / ${totalPages}`, PAGE_W - MARGIN, 292, { align: 'right' })
  }

  const filename = `Raizen_${result.destinationName.replace(/\s/g, '_')}_${result.days}Day_Trip.pdf`
  doc.save(filename)
}
